FROM microsoft/dotnet:2.2-aspnetcore-runtime

RUN apt-get update && apt-get install -y net-tools iputils-ping && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

EXPOSE 5000

VOLUME ["/app/logfile"]

ENTRYPOINT ["dotnet","WebCore.dll"]